"""add missing scripts

Revision ID: 8bfe3c053bdf
Revises: b59eb67cd078
Create Date: 2024-02-13 21:46:59.862637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8bfe3c053bdf"
down_revision: Union[str, None] = "b59eb67cd078"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("question_form_id_fkey", "question", type_="foreignkey")
    op.drop_column("question", "form_id")
    op.drop_column("question", "steps")
    op.drop_column("question", "max")
    op.drop_column("question", "min")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question", sa.Column("min", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "question", sa.Column("max", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "question", sa.Column("steps", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "question",
        sa.Column("form_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "question_form_id_fkey", "question", "form", ["form_id"], ["id"]
    )
    # ### end Alembic commands ###
